# Generated by Django 5.1.1 on 2024-10-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_user_status_delete_referral'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
